return {
    background = Color3.fromHex("#2C2F33"),
    background2 = Color3.fromHex("#222427"),

    text = Color3.fromHex("#DCE1E5"),
    text2 = Color3.fromHex("#737C8A"),

    selectedTab = Color3.fromHex("#1A1A1B"),

    colorpickerBar = Color3.fromHex("#DCE1E5"),

    notificationButton = Color3.fromHex("#222427"),

    mobileButtonBackground = Color3.fromHex("#DCE1E5"),
    mobileButtonText = Color3.fromHex("#2C2F33"),
    mobileButtonImage = Color3.fromHex("#2C2F33"),

    disabledBackground = Color3.fromHex("#2A2C31"),
    disabledText = Color3.fromHex("#D6DCE0"),

    toggled = Color3.fromHex("#DCE1E5"),

    red = Color3.fromRGB(255,105,97),
    orange = Color3.fromHex("#ff9b61")
}